version: '3.5'
services:

  php_service:
    build:
      context: ./docker/php/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/var/www/html/
    container_name : api_picolo_php_container
    image : api_picolo_php_image
    restart: always
#    networks:
#      - api_allopico_net


  apache_service:
    container_name: api_picolo_apache_container
    image: api_picolo_apache_image
    build:
      context: ./docker/apache/
    ports:
      - "${APACHE_PORT}:80"
    restart: always
    volumes:
      - .:/var/www/html/
#    networks:
#      api_allopico_net:
#        ipv4_address: 172.98.1.4
    depends_on:
      - php_service

#networks:
#  api_allopico_net:
#    name: api_allopico-net
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.98.0.0/16
